<?php
/**
 * Catalog advanced sidebar search box
 *
 * @see Inchoo_CatalogSearch_Block_Advanced_Sidebar
 */
?>
<style type="text/css">
.mini-advanced-search select, 
.mini-advanced-search input.input-text { width: 100%; }
.mini-advanced-search .input-range img { display: inline; }
</style>

<?php $maxQueryLength= $this->helper('catalogsearch')->getMaxQueryLength();?>
<div class="block mini-advanced-search">
	<div class="block-title">
		<strong><span><?php echo $this->__('Advanced Search') ?></span></strong>
	</div>
	<div class="block-content">
		<form action="<?php echo $this->getUrl('catalogsearch/advanced/result'); ?>" method="get" id="mini-advanced-search-form">

			<ul id="advanced-search-list" class="form-list">
				<?php foreach ($this->getSearchableAttributes() as $_attribute): ?>
				<?php $_code = $_attribute->getAttributeCode() ?>
				<li>
					<label for="<?php echo $_code ?>"><?php echo $this->getAttributeLabel($_attribute) ?></label>
	
					<?php switch($this->getAttributeInputType($_attribute)):
						case 'number': ?>
						<div class="input-range">
							<input type="text" name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" maxlength="<?php echo $maxQueryLength;?>" />
							<span class="separator">-</span>
							<input type="text" name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" maxlength="<?php echo $maxQueryLength;?>" />
						</div>
						<?php break;
						case 'price': ?>
						<div class="input-range">
							<input name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" maxlength="<?php echo $maxQueryLength;?>" />
							<span class="separator">-</span>
							<input name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" maxlength="<?php echo $maxQueryLength;?>" />
							<small>(<?php echo $this->getCurrency($_attribute); ?>)</small>
						</div>
						<?php break;
						case 'select': ?>
							<div class="input-box">
								<?php echo $this->getAttributeSelectElement($_attribute) ?>
							</div>
						<?php break;
						case 'yesno': ?>
							<?php echo $this->getAttributeYesNoElement($_attribute) ?>
						<?php break;
						case 'date': ?>
						<div class="input-range">
							<?php echo $this->getDateInput($_attribute, 'from') ?>
							<span class="separator">-</span>
							<?php echo $this->getDateInput($_attribute, 'to') ?>
						</div>
						<?php break;
						default: ?>
						<div class="input-box">
							<input type="text" name="<?php echo $_code ?>" id="<?php echo $_code ?>" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute)) ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text <?php echo $this->getAttributeValidationClass($_attribute) ?>" maxlength="<?php echo $maxQueryLength;?>" />
						</div>
					<?php endswitch; ?>
				</li>
				<?php endforeach; ?>
			</ul>
		
			<div id="mini-advanced-search-validation" style="display:none;" class="validation-advice"><?php echo $this->__('Please specify at least one search term.'); ?></div>
		
			<div class="actions">
				<button class="button" type="submit"><span><?php echo $this->__('Search') ?></span></button>
			</div>
		</form>

	</div>

</div>

<?php // simple validation example ?>
<script type="text/javascript">
$('mini-advanced-search-form').observe('submit', function(e) {
	var validated = this.getElements().any(function(el) { return el.getValue(); });
	
	if(!validated) {
		$('mini-advanced-search-validation').show();
		this.getElements().invoke('enable');
		Event.stop(e);
	} else {
		$('mini-advanced-search-validation').hide();
	}
});
</script>
