
<script type="text/javascript">
    jQuery(function( $ ){
        var container = $("#toggleTextMenu");
        $("#displayTextMenu").click(
        function( event ){
            event.preventDefault();
            if (container.is( ":visible" )){
                container.slideUp(1000);
                $("#displayTextMenu").removeClass('hidden-arrow');
                $("#displayTextMenu").attr('title', 'show menu')
                
                
            } else {
                container.slideDown(1000);
                $("#displayTextMenu").toggleClass('hidden-arrow');
                $("#displayTextMenu").attr('title', 'hide menu');
            }
        }
        );         
    });              
</script>

<?php
    $page = Mage::app()->getFrontController()->getRequest()->getRouteName();
    $homePage = false;

    if($page =='cms'){
        $cmsSingletonIdentifier = Mage::getSingleton('cms/page')->getIdentifier();
        $homeIdentifier = Mage::app()->getStore()->getConfig('web/default/cms_home_page');
        if($cmsSingletonIdentifier === $homeIdentifier){
            $homePage = true;
        }
    }

?>
<div id="hidden-menu" class="menu-hidden-desktop" style="display: none;">
    <a class="option" id="displayTextMenu" href="#" title="show menu" style=""><span>Navigation</span></a>
    <div id="toggleTextMenu" style="display: none;">
        <div class="menu-resize-inner">
            <div class="menu-resize-inner-content">
                <?php echo $this->getChildHtml('topMenuResize'); ?>
            </div>
        </div>
    </div>
</div>
<div class="menu-wrapper">
        <script type="text/javascript">
            jQuery(function( $ ){
                var container = $("#menu-default");
                var isMobile = /iPhone|iPod|iPad|Phone|Mobile|Android|hpwos/i.test(navigator.userAgent);
            
            if(!isMobile){
                if (!($("body").hasClass("cms-index-index"))){
                    $(".menu-wrapper").hover(
                    /*function( event ){
                        event.preventDefault();
                        if (container.is( ":visible" )){
                            container.slideUp(200);
                            $("#menuleftText").removeClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'show-option');
                        } else {
                            container.slideDown(200);
                            $("#menuleftText").toggleClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'hide-option');                
                        }
                    }*/
                        function(){
                            container.fadeIn(500);
                            $("#menuleftText").toggleClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'hide-option');
                        },
                        function(){
                            container.fadeOut(100);
                            $("#menuleftText").removeClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'show-option');
                        }
                    );
                }
            }else{
                $("#menuleftText").click(
                function( event ){
                    event.preventDefault();
                    if (container.is( ":visible" )){
                        container.hide();
                        $("#menuleftText").removeClass('hidden-arrow');
                        $("#menuleftText").attr('title', 'show-option');
                        
                        
                    } else {
                        container.show();
                        $("#menuleftText").toggleClass('hidden-arrow');
                        $("#menuleftText").attr('title', 'hide-option');
                    }
                }
                );
            }              
            });         
        </script>
        <div class="all_categories"<?php if (!$homePage): echo ' id="menuleftText"'; endif; ?>>
            <div class="menuleftText-title"><div class="menuleftText" ><span><?php echo $this->__('All Categories') ?></span></div></div>
        </div>
    <div class="menuleft">
        <?php
            $url = Mage::helper("core/url")->getCurrentUrl();
            $url_check = "themeframework_admin/area/preview";
        ?>
        <div id="menu-default" class="mega-menu" <?php if ($homePage || stripos($url, $url_check) == true): echo 'style="display: block;"'; else: echo 'style="display: none;"'; endif; ?> >
            
                <?php echo $this->getChildHtml('topMenu'); ?>
        </div>
    </div>
</div>