
<script type="text/javascript">
    jQuery(function( $ ){
        var container = $("#toggleTextMenu");
        $("#displayTextMenu").click(
        function( event ){
            event.preventDefault();
            if (container.is( ":visible" )){
                container.slideUp(1000);
                $("#displayTextMenu").removeClass('hidden-arrow');
                $("#displayTextMenu").attr('title', 'show menu')
                
                
            } else {
                container.slideDown(1000);
                $("#displayTextMenu").toggleClass('hidden-arrow');
                $("#displayTextMenu").attr('title', 'hide menu');
            }
        }
        );         
    });              
</script>

<?php 
$root = Mage::app()->getLayout()->getBlock('root');
$layout = Mage::getSingleton('core/layout');
$updates = $layout->getUpdate();
$xml = $updates->asString();
$area17Html = $this->getLayout()->getBlock('em_area17')->getChild();

//var_dump($xml);
/*if ($root) {
    $rootTpl = $root->getTemplate(); // For core/design_package calculated
                                     // absolute path use getTemplateFile();
    $flag = true;

    switch ($rootTpl) {

        case 'page/2columns-left.phtml':
            $flag = false;
            break;

        case 'page/3columns.phtml':
            $flag = false;
            break;
    }
}*/
$page = Mage::getSingleton('cms/page')->getIdentifier();
//if($area17Html || $page == 'galaelectronues_home'):
?>
<div id="hidden-menu" class="menu-hidden-desktop" style="display: none;">
    <a class="option" id="displayTextMenu" href="#" title="show menu" style=""><span>Navigation</span></a>
    <div id="toggleTextMenu" style="display: none;">
        <div class="menu-resize-inner">
            <div class="menu-resize-inner-content">
                <?php echo $this->getChildHtml('topMenuResize'); ?>
            </div>
        </div>
    </div>
</div>
<div class="menu-wrapper">
        <script type="text/javascript">
            jQuery(function( $ ){
                var container = $("#menu-default");
                var isMobile = /iPhone|iPod|iPad|Phone|Mobile|Android|hpwos/i.test(navigator.userAgent);
            
            if(!isMobile){
                if (!($("body").hasClass("cms-index-index"))){
                    $(".menu-wrapper").hover(
                    /*function( event ){
                        event.preventDefault();
                        if (container.is( ":visible" )){
                            container.slideUp(200);
                            $("#menuleftText").removeClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'show-option');
                        } else {
                            container.slideDown(200);
                            $("#menuleftText").toggleClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'hide-option');                
                        }
                    }*/
                        function(){
                            container.fadeIn(500);
                            $("#menuleftText").toggleClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'hide-option');
                        },
                        function(){
                            container.fadeOut(100);
                            $("#menuleftText").removeClass('hidden-arrow');
                            $("#menuleftText").attr('title', 'show-option');
                        }
                    );
                }
            }else{
                $("#menuleftText").click(
                function( event ){
                    event.preventDefault();
                    if (container.is( ":visible" )){
                        container.hide();
                        $("#menuleftText").removeClass('hidden-arrow');
                        $("#menuleftText").attr('title', 'show-option');
                        
                        
                    } else {
                        container.show();
                        $("#menuleftText").toggleClass('hidden-arrow');
                        $("#menuleftText").attr('title', 'hide-option');
                    }
                }
                );
            }              
            });         
        </script>
        <div class="all_categories"<?php if ($page != 'galaelectronues_home'): echo ' id="menuleftText"'; endif; ?>>
            <div class="menuleftText-title"><div class="menuleftText" ><span><?php echo $this->__('All Categories') ?></span></div></div>
        </div>
    <div class="menuleft">
        <?php
            $url = Mage::helper("core/url")->getCurrentUrl();
            $url_check = "themeframework_admin/area/preview";
        ?>
        <div id="menu-default" class="mega-menu" <?php if ($page == 'galaelectronues_home' || stripos($url, $url_check) == true): echo 'style="display: block;"'; else: echo 'style="display: none;"'; endif; ?> >
            
                <?php echo $this->getChildHtml('topMenu'); ?>
        </div>
    </div>
</div>
<?php
//endif;
?>